# Generated by Django 5.0.1 on 2024-01-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=264)),
                ('author', models.CharField(max_length=264)),
                ('price', models.FloatField(blank=True)),
            ],
        ),
    ]
