# Generated by Django 5.0.1 on 2024-02-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=264)),
                ('author', models.CharField(max_length=264)),
                ('genre', models.CharField(blank=True, max_length=264)),
                ('price', models.FloatField(blank=True)),
            ],
        ),
    ]
