# Generated by Django 5.0.1 on 2024-02-07 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author_api', '0001_initial'),
        ('publication_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=264)),
                ('genre', models.CharField(blank=True, max_length=264)),
                ('price', models.FloatField(blank=True)),
                ('authors', models.ManyToManyField(to='author_api.author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication_api.publication')),
            ],
        ),
    ]
