# Generated by Django 5.0.1 on 2024-02-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('arrival_time', models.CharField(max_length=5)),
                ('departure_time', models.CharField(max_length=5)),
                ('fare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('wallet_id', models.IntegerField()),
                ('station_from', models.IntegerField()),
                ('station_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.IntegerField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('stops', models.ManyToManyField(related_name='train_stops', to='API.stop')),
            ],
        ),
    ]
